### ISSUE TITLE
Collected movie list overwriting itself

### ISSUE THREAD

**Issue by dylan-sloan** [dylan-sloan/MovieSafe#2]
### Issue
When clearing the watched movies from the watch list, any movies that were already in the "collectedMovies" localStorage object get overwritten by the new movies getting set as this variable. 
### Possible Solution
Solution is not as simple as turning this object into an array and appending to it - have tried this and doesn't take kindly. I believe the solution to be converting the storage from chrome's localStorage to a backend database, as this should allow more control over the data stored.

**Comment by JTPerdue525** [comment]
I see you have an issue.

**Comment by dylan-sloan** [comment]
Added logic in the Home.js function `handleClearList` to stop overwriting of the collected movies whilst still maintaining the data in local storage rather than a database.
